// ── APP DATA ──────────────────────────────────────────────────────────────────

const HOME_CATEGORIES = [
  { id:'ai',           label:'AI',            emoji:'🤖', grad:'from-violet-600 to-purple-700' },
  { id:'kids',         label:'Kids',          emoji:'👶', grad:'from-yellow-400 to-orange-500' },
  { id:'ecommerce',    label:'E-Commerce',    emoji:'🛒', grad:'from-orange-500 to-red-600'    },
  { id:'business',     label:'Business',      emoji:'💼', grad:'from-blue-600 to-indigo-700'   },
  { id:'beauty',       label:'Beauty',        emoji:'💄', grad:'from-pink-500 to-rose-600'     },
  { id:'artdesign',    label:'Art & Design',  emoji:'🎨', grad:'from-purple-500 to-fuchsia-600'},
  { id:'finance',      label:'Finance',       emoji:'💰', grad:'from-green-500 to-emerald-700' },
  { id:'education',    label:'Education',     emoji:'📚', grad:'from-indigo-500 to-blue-700'   },
  { id:'entertainment',label:'Entertainment', emoji:'🎬', grad:'from-red-500 to-pink-600'      },
  { id:'tools',        label:'Tools',         emoji:'🔧', grad:'from-slate-500 to-gray-700'    },
  { id:'health',       label:'Health',        emoji:'🏃', grad:'from-teal-500 to-cyan-600'     },
  { id:'social',       label:'Social',        emoji:'💬', grad:'from-sky-500 to-blue-600'      },
];

const APPS = [
  // AI
  {id:'ai1',  name:'ChatGPT',       domain:'openai.com',           homeCategory:'ai',           mode:'study', emoji:'🤖', url:'https://chat.openai.com',           category:'AI',          tags:['ai','assistant','gpt'],           rating:4.8, reviews:'12.5K', desc:'Chat, ask questions, get instant answers and write anything.'},
  {id:'ai2',  name:'Claude',        domain:'claude.ai',             homeCategory:'ai',           mode:'study', emoji:'🦙', url:'https://claude.ai',                 category:'AI',          tags:['ai','assistant','claude'],         rating:4.7, reviews:'8K',   desc:'AI assistant by Anthropic — thoughtful and nuanced responses.'},
  {id:'ai3',  name:'Gemini',        domain:'gemini.google.com',     homeCategory:'ai',           mode:'study', emoji:'✨', url:'https://gemini.google.com',         category:'AI',          tags:['ai','google','assistant'],         rating:4.6, reviews:'20K',  desc:'Google Gemini — multimodal AI for text, images and more.'},
  {id:'ai4',  name:'Perplexity',    domain:'perplexity.ai',         homeCategory:'ai',           mode:'study', emoji:'🔮', url:'https://www.perplexity.ai',         category:'AI',          tags:['ai','search','research'],          rating:4.7, reviews:'15K',  desc:'AI-powered search engine with cited real-time answers.'},
  {id:'ai5',  name:'Midjourney',    domain:'midjourney.com',        homeCategory:'ai',           mode:'play',  emoji:'🖼️', url:'https://www.midjourney.com',        category:'AI Art',      tags:['ai','image','art'],                rating:4.8, reviews:'30K',  desc:'Generate stunning images from text prompts with AI.'},
  {id:'ai6',  name:'Copilot',       domain:'microsoft.com',         homeCategory:'ai',           mode:'work',  emoji:'🧠', url:'https://copilot.microsoft.com',     category:'AI',          tags:['ai','microsoft','code'],           rating:4.5, reviews:'25K',  desc:'Microsoft Copilot — AI for coding, writing, and more.'},
  // KIDS
  {id:'kid1', name:'Khan Kids',     domain:'khanacademy.org',       homeCategory:'kids',         mode:'study', emoji:'🧒', url:'https://www.khanacademy.org/kids',  category:'Kids',        tags:['kids','learning','fun'],           rating:4.9, reviews:'50K',  desc:'Free educational app for kids ages 2–8.'},
  {id:'kid2', name:'Duolingo',      domain:'duolingo.com',          homeCategory:'kids',         mode:'study', emoji:'🦉', url:'https://www.duolingo.com',          category:'Language',    tags:['kids','language','learning'],      rating:4.8, reviews:'200K', desc:'Learn languages in just 5 minutes a day.'},
  {id:'kid3', name:'Scratch',       domain:'scratch.mit.edu',       homeCategory:'kids',         mode:'play',  emoji:'🐱', url:'https://scratch.mit.edu',           category:'Coding',      tags:['kids','coding','creative'],        rating:4.7, reviews:'18K',  desc:'Create interactive stories, games, and animations.'},
  {id:'kid4', name:'Toca Boca',     domain:'tocaboca.com',          homeCategory:'kids',         mode:'play',  emoji:'🧸', url:'https://tocaboca.com',              category:'Kids',        tags:['kids','play','creative'],          rating:4.8, reviews:'40K',  desc:'Digital toys and play worlds for children.'},
  {id:'kid5', name:'ABCmouse',      domain:'abcmouse.com',          homeCategory:'kids',         mode:'study', emoji:'🔡', url:'https://www.abcmouse.com',          category:'Education',   tags:['kids','abc','preschool'],          rating:4.6, reviews:'22K',  desc:'Early learning academy covering reading, math and more.'},
  {id:'kid6', name:'Coolmath',      domain:'coolmathgames.com',     homeCategory:'kids',         mode:'study', emoji:'🎮', url:'https://www.coolmathgames.com',     category:'Math',        tags:['kids','math','games'],             rating:4.5, reviews:'12K',  desc:'Fun math games for kids of all ages.'},
  // E-COMMERCE
  {id:'ec1',  name:'Amazon',        domain:'amazon.com',            homeCategory:'ecommerce',    mode:'play',  emoji:'📦', url:'https://www.amazon.com',            category:'Shopping',    tags:['shopping','amazon','deals'],       rating:4.7, reviews:'1M',   desc:'Shop millions of products with fast delivery.'},
  {id:'ec2',  name:'Shopify',       domain:'shopify.com',           homeCategory:'ecommerce',    mode:'work',  emoji:'🏪', url:'https://www.shopify.com',           category:'Store',       tags:['ecommerce','store','sell'],        rating:4.6, reviews:'80K',  desc:'Build and run your own online store.'},
  {id:'ec3',  name:'Etsy',          domain:'etsy.com',              homeCategory:'ecommerce',    mode:'play',  emoji:'🎁', url:'https://www.etsy.com',              category:'Handmade',    tags:['handmade','crafts','shop'],        rating:4.7, reviews:'200K', desc:'Buy and sell unique handmade and vintage goods.'},
  {id:'ec4',  name:'eBay',          domain:'ebay.com',              homeCategory:'ecommerce',    mode:'play',  emoji:'🔨', url:'https://www.ebay.com',              category:'Auction',     tags:['auction','shopping','deals'],      rating:4.5, reviews:'300K', desc:'Buy and sell new and used items worldwide.'},
  {id:'ec5',  name:'WooCommerce',   domain:'woocommerce.com',       homeCategory:'ecommerce',    mode:'work',  emoji:'🛍️', url:'https://woocommerce.com',           category:'Store',       tags:['ecommerce','wordpress','store'],   rating:4.4, reviews:'30K',  desc:'Open-source ecommerce for WordPress.'},
  {id:'ec6',  name:'Stripe',        domain:'stripe.com',            homeCategory:'ecommerce',    mode:'work',  emoji:'💳', url:'https://stripe.com',               category:'Payments',    tags:['payments','checkout','api'],       rating:4.8, reviews:'60K',  desc:'Payments infrastructure for the internet.'},
  // BUSINESS
  {id:'biz1', name:'Notion',        domain:'notion.so',             homeCategory:'business',     mode:'work',  emoji:'📝', url:'https://www.notion.so',             category:'Notes',       tags:['notes','productivity','wiki'],     rating:4.9, reviews:'98K',  desc:'All-in-one workspace for notes, docs, and databases.'},
  {id:'biz2', name:'Slack',         domain:'slack.com',             homeCategory:'business',     mode:'work',  emoji:'💬', url:'https://slack.com',                category:'Chat',        tags:['chat','team','messaging'],         rating:4.6, reviews:'120K', desc:'Your productivity platform for team collaboration.'},
  {id:'biz3', name:'Trello',        domain:'trello.com',            homeCategory:'business',     mode:'work',  emoji:'📋', url:'https://trello.com',               category:'Kanban',      tags:['tasks','kanban','project'],        rating:4.7, reviews:'80K',  desc:'Organize your work with boards, lists and cards.'},
  {id:'biz4', name:'Zoom',          domain:'zoom.us',               homeCategory:'business',     mode:'work',  emoji:'📹', url:'https://zoom.us',                  category:'Video',       tags:['meetings','video','calls'],        rating:4.5, reviews:'500K', desc:'Video meetings, webinars, and phone calls.'},
  {id:'biz5', name:'Linear',        domain:'linear.app',            homeCategory:'business',     mode:'work',  emoji:'🔷', url:'https://linear.app',               category:'Projects',    tags:['issues','sprints','engineering'],  rating:4.8, reviews:'15K',  desc:'The issue tracker built for modern software teams.'},
  {id:'biz6', name:'Loom',          domain:'loom.com',              homeCategory:'business',     mode:'work',  emoji:'🎥', url:'https://www.loom.com',              category:'Video',       tags:['video','record','async'],          rating:4.7, reviews:'25K',  desc:'Record quick video messages for your team.'},
  // BEAUTY
  {id:'bty1', name:'Pinterest',     domain:'pinterest.com',         homeCategory:'beauty',       mode:'play',  emoji:'📌', url:'https://www.pinterest.com',         category:'Inspiration', tags:['beauty','fashion','ideas'],        rating:4.7, reviews:'500K', desc:'Discover ideas for beauty, fashion, home and more.'},
  {id:'bty2', name:'Canva',         domain:'canva.com',             homeCategory:'beauty',       mode:'work',  emoji:'✏️', url:'https://www.canva.com',             category:'Design',      tags:['beauty','design','templates'],     rating:4.8, reviews:'180K', desc:'Create stunning beauty content and social posts.'},
  {id:'bty3', name:'VSCO',          domain:'vsco.co',               homeCategory:'beauty',       mode:'play',  emoji:'📷', url:'https://vsco.co',                  category:'Photo',       tags:['photo','filter','beauty'],         rating:4.6, reviews:'90K',  desc:'Edit your photos and videos with creative tools.'},
  {id:'bty4', name:'Lightroom',     domain:'adobe.com',             homeCategory:'beauty',       mode:'work',  emoji:'🌅', url:'https://lightroom.adobe.com',       category:'Photo',       tags:['photo','edit','adobe'],            rating:4.7, reviews:'150K', desc:'Professional photo editing anywhere, anytime.'},
  {id:'bty5', name:'YouCam',        domain:'perfectcorp.com',       homeCategory:'beauty',       mode:'play',  emoji:'💅', url:'https://www.perfectcorp.com',       category:'Makeup',      tags:['makeup','beauty','try-on'],        rating:4.5, reviews:'40K',  desc:'Virtual makeup try-on powered by AI.'},
  {id:'bty6', name:'Unfold',        domain:'unfold.com',            homeCategory:'beauty',       mode:'play',  emoji:'🌸', url:'https://unfold.com',                category:'Stories',     tags:['stories','beauty','templates'],    rating:4.6, reviews:'35K',  desc:'Create beautiful stories with aesthetic templates.'},
  // ART & DESIGN
  {id:'art1', name:'Figma',         domain:'figma.com',             homeCategory:'artdesign',    mode:'work',  emoji:'🎨', url:'https://www.figma.com',             category:'Design',      tags:['design','ui','prototype'],         rating:4.9, reviews:'60K',  desc:'The collaborative interface design tool.'},
  {id:'art2', name:'Adobe XD',      domain:'adobe.com',             homeCategory:'artdesign',    mode:'work',  emoji:'🔵', url:'https://www.adobe.com/products/xd.html', category:'Design',tags:['design','adobe','ux'],            rating:4.6, reviews:'45K',  desc:'Design and prototype user experiences with Adobe XD.'},
  {id:'art3', name:'Spline',        domain:'spline.design',         homeCategory:'artdesign',    mode:'work',  emoji:'🌀', url:'https://spline.design',             category:'3D',          tags:['3d','design','interactive'],       rating:4.7, reviews:'12K',  desc:'Design and collaborate in 3D with ease.'},
  {id:'art4', name:'Procreate',     domain:'procreate.com',         homeCategory:'artdesign',    mode:'play',  emoji:'🖌️', url:'https://procreate.com',             category:'Drawing',     tags:['drawing','illustration','art'],    rating:4.9, reviews:'200K', desc:'Powerful illustration app for creative professionals.'},
  {id:'art5', name:'Coolors',       domain:'coolors.co',            homeCategory:'artdesign',    mode:'work',  emoji:'🌈', url:'https://coolors.co',               category:'Colors',      tags:['colors','palette','design'],       rating:4.7, reviews:'20K',  desc:'Generate beautiful color palettes in seconds.'},
  {id:'art6', name:'Dribbble',      domain:'dribbble.com',          homeCategory:'artdesign',    mode:'work',  emoji:'🏀', url:'https://dribbble.com',              category:'Portfolio',   tags:['design','portfolio','inspiration'],rating:4.6, reviews:'40K',  desc:'Discover the world\'s top designers and creatives.'},
  // FINANCE
  {id:'fin1', name:'PayPal',        domain:'paypal.com',            homeCategory:'finance',      mode:'work',  emoji:'💰', url:'https://www.paypal.com',            category:'Payments',    tags:['payments','money','transfer'],     rating:4.5, reviews:'600K', desc:'Send and receive money safely with PayPal.'},
  {id:'fin2', name:'Wise',          domain:'wise.com',              homeCategory:'finance',      mode:'work',  emoji:'🌍', url:'https://wise.com',                  category:'Transfer',    tags:['money','international','transfer'],rating:4.7, reviews:'80K',  desc:'Send money abroad at real exchange rates.'},
  {id:'fin3', name:'CoinGecko',     domain:'coingecko.com',         homeCategory:'finance',      mode:'work',  emoji:'🦎', url:'https://www.coingecko.com',         category:'Crypto',      tags:['crypto','bitcoin','prices'],       rating:4.6, reviews:'30K',  desc:'Track crypto prices, charts and market data.'},
  {id:'fin4', name:'Yahoo Finance', domain:'yahoo.com',             homeCategory:'finance',      mode:'work',  emoji:'📈', url:'https://finance.yahoo.com',         category:'Stocks',      tags:['stocks','finance','market'],       rating:4.5, reviews:'200K', desc:'Stock quotes, financial news, and portfolio tracking.'},
  {id:'fin5', name:'YNAB',          domain:'youneedabudget.com',    homeCategory:'finance',      mode:'work',  emoji:'📊', url:'https://www.youneedabudget.com',    category:'Budget',      tags:['budget','money','savings'],        rating:4.8, reviews:'25K',  desc:'Stop living paycheck to paycheck with smart budgeting.'},
  {id:'fin6', name:'Coinbase',      domain:'coinbase.com',          homeCategory:'finance',      mode:'work',  emoji:'🪙', url:'https://www.coinbase.com',          category:'Crypto',      tags:['crypto','buy','exchange'],         rating:4.4, reviews:'150K', desc:'Buy, sell, and manage your cryptocurrency portfolio.'},
  // EDUCATION
  {id:'edu1', name:'Khan Academy',  domain:'khanacademy.org',       homeCategory:'education',    mode:'study', emoji:'📚', url:'https://www.khanacademy.org',       category:'Learning',    tags:['learning','math','science'],       rating:4.8, reviews:'45K',  desc:'Free world-class education for anyone, anywhere.'},
  {id:'edu2', name:'Coursera',      domain:'coursera.org',          homeCategory:'education',    mode:'study', emoji:'🎓', url:'https://www.coursera.org',          category:'Courses',     tags:['courses','certificates'],          rating:4.7, reviews:'60K',  desc:'Learn from world-class universities and companies.'},
  {id:'edu3', name:'Quizlet',       domain:'quizlet.com',           homeCategory:'education',    mode:'study', emoji:'🃏', url:'https://quizlet.com',               category:'Flashcards',  tags:['flashcards','memory','study'],     rating:4.7, reviews:'55K',  desc:'Make flashcards and study smarter.'},
  {id:'edu4', name:'Wolfram Alpha', domain:'wolframalpha.com',      homeCategory:'education',    mode:'study', emoji:'🔢', url:'https://www.wolframalpha.com',      category:'Calculator',  tags:['math','calculator','answers'],     rating:4.7, reviews:'8K',   desc:'Computational intelligence for any question.'},
  {id:'edu5', name:'Desmos',        domain:'desmos.com',            homeCategory:'education',    mode:'study', emoji:'📐', url:'https://www.desmos.com',            category:'Calculator',  tags:['math','graphing'],                 rating:4.7, reviews:'8K',   desc:'Powerful graphing calculator for math and science.'},
  {id:'edu6', name:'MIT OpenCourse',domain:'mit.edu',               homeCategory:'education',    mode:'study', emoji:'🏛️', url:'https://ocw.mit.edu',               category:'Courses',     tags:['university','courses','free'],     rating:4.8, reviews:'20K',  desc:'Free MIT courseware — learn from the best university.'},
  // ENTERTAINMENT
  {id:'ent1', name:'YouTube',       domain:'youtube.com',           homeCategory:'entertainment',mode:'play',  emoji:'▶️', url:'https://www.youtube.com',           category:'Video',       tags:['video','music','entertainment'],   rating:4.8, reviews:'1M',   desc:'Watch, share and discover videos worldwide.'},
  {id:'ent2', name:'Spotify',       domain:'spotify.com',           homeCategory:'entertainment',mode:'play',  emoji:'🎵', url:'https://open.spotify.com',          category:'Music',       tags:['music','podcast','audio'],         rating:4.9, reviews:'900K', desc:'Music for everyone, free and ad-supported.'},
  {id:'ent3', name:'Twitch',        domain:'twitch.tv',             homeCategory:'entertainment',mode:'play',  emoji:'🟣', url:'https://www.twitch.tv',             category:'Streaming',   tags:['streaming','gaming','live'],       rating:4.7, reviews:'150K', desc:'Watch live game streams and connect with creators.'},
  {id:'ent4', name:'Reddit',        domain:'reddit.com',            homeCategory:'entertainment',mode:'play',  emoji:'🤖', url:'https://www.reddit.com',            category:'Social',      tags:['social','community','news'],       rating:4.5, reviews:'400K', desc:'The front page of the internet.'},
  {id:'ent5', name:'SoundCloud',    domain:'soundcloud.com',        homeCategory:'entertainment',mode:'play',  emoji:'🔊', url:'https://soundcloud.com',            category:'Music',       tags:['music','indie','upload'],          rating:4.6, reviews:'60K',  desc:'Discover and share music from independent artists.'},
  {id:'ent6', name:'GeoGuessr',     domain:'geoguessr.com',         homeCategory:'entertainment',mode:'play',  emoji:'🌍', url:'https://www.geoguessr.com',         category:'Game',        tags:['geography','maps','explore'],      rating:4.7, reviews:'30K',  desc:'Explore the world through Google Street View.'},
  // TOOLS
  {id:'tol1', name:'Smallpdf',      domain:'smallpdf.com',          homeCategory:'tools',        mode:'study', emoji:'📋', url:'https://smallpdf.com',              category:'PDF Tools',   tags:['pdf','compress','convert'],        rating:4.6, reviews:'30K',  desc:'All-in-one PDF tool — compress, convert, edit.'},
  {id:'tol2', name:'iLovePDF',      domain:'ilovepdf.com',          homeCategory:'tools',        mode:'study', emoji:'❤️', url:'https://www.ilovepdf.com',          category:'PDF',         tags:['pdf','merge','split'],             rating:4.7, reviews:'18K',  desc:'Merge, split, compress and convert PDFs with ease.'},
  {id:'tol3', name:'Pomofocus',     domain:'pomofocus.io',          homeCategory:'tools',        mode:'study', emoji:'🍅', url:'https://pomofocus.io',              category:'Focus',       tags:['pomodoro','focus','timer'],        rating:4.5, reviews:'6K',   desc:'A Pomodoro timer to stay focused on your tasks.'},
  {id:'tol4', name:'GitHub',        domain:'github.com',            homeCategory:'tools',        mode:'work',  emoji:'🐙', url:'https://github.com',               category:'Code',        tags:['code','git','repository'],         rating:4.8, reviews:'100K', desc:'Where the world builds software together.'},
  {id:'tol5', name:'Google Docs',   domain:'google.com',            homeCategory:'tools',        mode:'study', emoji:'📄', url:'https://docs.google.com',           category:'Documents',   tags:['docs','writing','google'],         rating:4.8, reviews:'500K', desc:'Create and collaborate on documents in real time.'},
  {id:'tol6', name:'Miro',          domain:'miro.com',              homeCategory:'tools',        mode:'work',  emoji:'🖼️', url:'https://miro.com',                  category:'Whiteboard',  tags:['whiteboard','brainstorm'],         rating:4.7, reviews:'40K',  desc:'The collaborative online whiteboard platform.'},
  // HEALTH
  {id:'hlt1', name:'MyFitnessPal',  domain:'myfitnesspal.com',      homeCategory:'health',       mode:'play',  emoji:'🏃', url:'https://www.myfitnesspal.com',      category:'Fitness',     tags:['fitness','calories','diet'],       rating:4.6, reviews:'200K', desc:'Track your food and exercise to reach your fitness goals.'},
  {id:'hlt2', name:'Headspace',     domain:'headspace.com',         homeCategory:'health',       mode:'play',  emoji:'🧘', url:'https://www.headspace.com',         category:'Meditation',  tags:['meditation','sleep','mindfulness'],rating:4.7, reviews:'100K', desc:'Meditation and mindfulness for any mind, any mood.'},
  {id:'hlt3', name:'Calm',          domain:'calm.com',              homeCategory:'health',       mode:'play',  emoji:'😌', url:'https://www.calm.com',              category:'Wellness',    tags:['sleep','meditation','calm'],       rating:4.8, reviews:'150K', desc:'Sleep, meditation, and relaxation app.'},
  {id:'hlt4', name:'Strava',        domain:'strava.com',            homeCategory:'health',       mode:'play',  emoji:'🚴', url:'https://www.strava.com',            category:'Running',     tags:['running','cycling','fitness'],     rating:4.6, reviews:'80K',  desc:'Track your runs, rides, and workouts with GPS.'},
  {id:'hlt5', name:'Cronometer',    domain:'cronometer.com',        homeCategory:'health',       mode:'play',  emoji:'🥗', url:'https://cronometer.com',            category:'Nutrition',   tags:['nutrition','food','health'],       rating:4.7, reviews:'30K',  desc:'Track your nutrition and health data accurately.'},
  {id:'hlt6', name:'Noom',          domain:'noom.com',              homeCategory:'health',       mode:'play',  emoji:'🌿', url:'https://www.noom.com',              category:'Diet',        tags:['weight','diet','coaching'],        rating:4.4, reviews:'60K',  desc:'Behavior-based approach to sustainable weight loss.'},
  // SOCIAL
  {id:'soc1', name:'Twitter / X',   domain:'twitter.com',           homeCategory:'social',       mode:'play',  emoji:'🐦', url:'https://twitter.com',              category:'Social',      tags:['social','news','trending'],        rating:4.3, reviews:'800K', desc:'See what\'s happening in the world right now.'},
  {id:'soc2', name:'LinkedIn',      domain:'linkedin.com',          homeCategory:'social',       mode:'work',  emoji:'💼', url:'https://www.linkedin.com',          category:'Network',     tags:['social','jobs','professional'],    rating:4.5, reviews:'500K', desc:'Professional networking and job search platform.'},
  {id:'soc3', name:'Discord',       domain:'discord.com',           homeCategory:'social',       mode:'play',  emoji:'🎮', url:'https://discord.com',              category:'Chat',        tags:['chat','gaming','community'],       rating:4.7, reviews:'300K', desc:'Voice, video, and text communication for communities.'},
  {id:'soc4', name:'Telegram',      domain:'telegram.org',          homeCategory:'social',       mode:'play',  emoji:'✈️', url:'https://web.telegram.org',         category:'Messaging',   tags:['messaging','private','groups'],    rating:4.8, reviews:'400K', desc:'Fast, secure, and powerful messaging app.'},
  {id:'soc5', name:'WhatsApp',      domain:'whatsapp.com',          homeCategory:'social',       mode:'play',  emoji:'📱', url:'https://web.whatsapp.com',          category:'Messaging',   tags:['messaging','calls','family'],      rating:4.7, reviews:'1M',   desc:'Simple, reliable, private messaging and calling.'},
  {id:'soc6', name:'Mastodon',      domain:'mastodon.social',       homeCategory:'social',       mode:'play',  emoji:'🐘', url:'https://mastodon.social',           category:'Social',      tags:['social','open source','fediverse'],rating:4.3, reviews:'15K',  desc:'Free and open-source decentralized social network.'},
];

const ALL_APPS = APPS;

const MODE_CFG = {
  study:{label:'Study', emoji:'🎓', subtitle:'Notes, calculators, AI tools and more', grad:'from-violet-600 to-indigo-800'},
  work: {label:'Work',  emoji:'💼', subtitle:'Documents, tools, productivity',         grad:'from-blue-600 to-blue-900'   },
  play: {label:'Play',  emoji:'🎮', subtitle:'Games, fun tools and entertainment',     grad:'from-emerald-500 to-green-800'},
};

function getAppsByHomeCategory(catId) {
  return APPS.filter(a => a.homeCategory === catId);
}
