// ── APP DATA ──────────────────────────────────────────────────────────────────

const HOME_CATEGORIES = [
  { id:'ai',           label:'AI',            emoji:'🤖', grad:'from-violet-600 to-purple-700', type:'app' },
  { id:'kids',         label:'Kids',          emoji:'👶', grad:'from-yellow-400 to-orange-500', type:'app' },
  { id:'ecommerce',    label:'E-Commerce',    emoji:'🛒', grad:'from-orange-500 to-red-600',    type:'app' },
  { id:'business',     label:'Business',      emoji:'💼', grad:'from-blue-600 to-indigo-700',   type:'app' },
  { id:'beauty',       label:'Beauty',        emoji:'💄', grad:'from-pink-500 to-rose-600',     type:'app' },
  { id:'artdesign',    label:'Art & Design',  emoji:'🎨', grad:'from-purple-500 to-fuchsia-600',type:'app' },
  { id:'finance',      label:'Finance',       emoji:'💰', grad:'from-green-500 to-emerald-700', type:'app' },
  { id:'education',    label:'Education',     emoji:'📚', grad:'from-indigo-500 to-blue-700',   type:'app' },
  { id:'entertainment',label:'Entertainment', emoji:'🎬', grad:'from-red-500 to-pink-600',      type:'app' },
  { id:'tools',        label:'Tools',         emoji:'🔧', grad:'from-slate-500 to-gray-700',    type:'app' },
  { id:'health',       label:'Health',        emoji:'🏃', grad:'from-teal-500 to-cyan-600',     type:'app' },
  { id:'social',       label:'Social',        emoji:'💬', grad:'from-sky-500 to-blue-600',      type:'app' },
];

const GAME_CATEGORIES = [
  { id:'puzzle',    label:'Puzzle',    emoji:'🧩', grad:'from-violet-500 to-indigo-600',  type:'game' },
  { id:'action',    label:'Action',    emoji:'⚔️', grad:'from-red-500 to-orange-600',     type:'game' },
  { id:'strategy',  label:'Strategy',  emoji:'♟️', grad:'from-blue-600 to-cyan-600',      type:'game' },
  { id:'arcade',    label:'Arcade',    emoji:'🕹️', grad:'from-pink-500 to-fuchsia-600',   type:'game' },
  { id:'word',      label:'Word',      emoji:'📝', grad:'from-green-500 to-teal-600',     type:'game' },
  { id:'casual',    label:'Casual',    emoji:'🎲', grad:'from-amber-400 to-orange-500',   type:'game' },
  { id:'sports',    label:'Sports',    emoji:'⚽', grad:'from-emerald-500 to-green-700',  type:'game' },
  { id:'adventure', label:'Adventure', emoji:'🗺️', grad:'from-orange-500 to-amber-600',   type:'game' },
];

const APPS = [
  // AI
  {id:'ai1',  name:'ChatGPT',       domain:'openai.com',           homeCategory:'ai',           mode:'study', emoji:'🤖', url:'https://chat.openai.com',           category:'AI',          tags:['ai','assistant','gpt'],           rating:4.8, reviews:'12.5K', description:'Chat, ask questions, get instant answers and write anything.'},
  {id:'ai2',  name:'Claude',        domain:'claude.ai',             homeCategory:'ai',           mode:'study', emoji:'🦙', url:'https://claude.ai',                 category:'AI',          tags:['ai','assistant','claude'],         rating:4.7, reviews:'8K',   description:'AI assistant by Anthropic — thoughtful and nuanced responses.'},
  {id:'ai3',  name:'Gemini',        domain:'gemini.google.com',     homeCategory:'ai',           mode:'study', emoji:'✨', url:'https://gemini.google.com',         category:'AI',          tags:['ai','google','assistant'],         rating:4.6, reviews:'20K',  description:'Google Gemini — multimodal AI for text, images and more.'},
  {id:'ai4',  name:'Perplexity',    domain:'perplexity.ai',         homeCategory:'ai',           mode:'study', emoji:'🔮', url:'https://www.perplexity.ai',         category:'AI',          tags:['ai','search','research'],          rating:4.7, reviews:'15K',  description:'AI-powered search engine with cited real-time answers.'},
  {id:'ai5',  name:'Midjourney',    domain:'midjourney.com',        homeCategory:'ai',           mode:'play',  emoji:'🖼️', url:'https://www.midjourney.com',        category:'AI Art',      tags:['ai','image','art'],                rating:4.8, reviews:'30K',  description:'Generate stunning images from text prompts with AI.'},
  {id:'ai6',  name:'Copilot',       domain:'microsoft.com',         homeCategory:'ai',           mode:'work',  emoji:'🧠', url:'https://copilot.microsoft.com',     category:'AI',          tags:['ai','microsoft','code'],           rating:4.5, reviews:'25K',  description:'Microsoft Copilot — AI for coding, writing, and more.'},
  // KIDS
  {id:'kid1', name:'Khan Kids',     domain:'khanacademy.org',       homeCategory:'kids',         mode:'study', emoji:'🧒', url:'https://www.khanacademy.org/kids',  category:'Kids',        tags:['kids','learning','fun'],           rating:4.9, reviews:'50K',  description:'Free educational app for kids ages 2–8.'},
  {id:'kid2', name:'Duolingo',      domain:'duolingo.com',          homeCategory:'kids',         mode:'study', emoji:'🦉', url:'https://www.duolingo.com',          category:'Language',    tags:['kids','language','learning'],      rating:4.8, reviews:'200K', description:'Learn languages in just 5 minutes a day.'},
  {id:'kid3', name:'Scratch',       domain:'scratch.mit.edu',       homeCategory:'kids',         mode:'play',  emoji:'🐱', url:'https://scratch.mit.edu',           category:'Coding',      tags:['kids','coding','creative'],        rating:4.7, reviews:'18K',  description:'Create interactive stories, games, and animations.'},
  {id:'kid4', name:'Toca Boca',     domain:'tocaboca.com',          homeCategory:'kids',         mode:'play',  emoji:'🧸', url:'https://tocaboca.com',              category:'Kids',        tags:['kids','play','creative'],          rating:4.8, reviews:'40K',  description:'Digital toys and play worlds for children.'},
  {id:'kid5', name:'ABCmouse',      domain:'abcmouse.com',          homeCategory:'kids',         mode:'study', emoji:'🔡', url:'https://www.abcmouse.com',          category:'Education',   tags:['kids','abc','preschool'],          rating:4.6, reviews:'22K',  description:'Early learning academy covering reading, math and more.'},
  {id:'kid6', name:'Coolmath',      domain:'coolmathgames.com',     homeCategory:'kids',         mode:'study', emoji:'🎮', url:'https://www.coolmathgames.com',     category:'Math',        tags:['kids','math','games'],             rating:4.5, reviews:'12K',  description:'Fun math games for kids of all ages.'},
  // E-COMMERCE
  {id:'ec1',  name:'Amazon',        domain:'amazon.com',            homeCategory:'ecommerce',    mode:'play',  emoji:'📦', url:'https://www.amazon.com',            category:'Shopping',    tags:['shopping','amazon','deals'],       rating:4.7, reviews:'1M',   description:'Shop millions of products with fast delivery.'},
  {id:'ec2',  name:'Shopify',       domain:'shopify.com',           homeCategory:'ecommerce',    mode:'work',  emoji:'🏪', url:'https://www.shopify.com',           category:'Store',       tags:['ecommerce','store','sell'],        rating:4.6, reviews:'80K',  description:'Build and run your own online store.'},
  {id:'ec3',  name:'Etsy',          domain:'etsy.com',              homeCategory:'ecommerce',    mode:'play',  emoji:'🎁', url:'https://www.etsy.com',              category:'Handmade',    tags:['handmade','crafts','shop'],        rating:4.7, reviews:'200K', description:'Buy and sell unique handmade and vintage goods.'},
  {id:'ec4',  name:'eBay',          domain:'ebay.com',              homeCategory:'ecommerce',    mode:'play',  emoji:'🔨', url:'https://www.ebay.com',              category:'Auction',     tags:['auction','shopping','deals'],      rating:4.5, reviews:'300K', description:'Buy and sell new and used items worldwide.'},
  {id:'ec5',  name:'WooCommerce',   domain:'woocommerce.com',       homeCategory:'ecommerce',    mode:'work',  emoji:'🛍️', url:'https://woocommerce.com',           category:'Store',       tags:['ecommerce','wordpress','store'],   rating:4.4, reviews:'30K',  description:'Open-source ecommerce for WordPress.'},
  {id:'ec6',  name:'Stripe',        domain:'stripe.com',            homeCategory:'ecommerce',    mode:'work',  emoji:'💳', url:'https://stripe.com',               category:'Payments',    tags:['payments','checkout','api'],       rating:4.8, reviews:'60K',  description:'Payments infrastructure for the internet.'},
  // BUSINESS
  {id:'biz1', name:'Notion',        domain:'notion.so',             homeCategory:'business',     mode:'work',  emoji:'📝', url:'https://www.notion.so',             category:'Notes',       tags:['notes','productivity','wiki'],     rating:4.9, reviews:'98K',  description:'All-in-one workspace for notes, docs, and databases.'},
  {id:'biz2', name:'Slack',         domain:'slack.com',             homeCategory:'business',     mode:'work',  emoji:'💬', url:'https://slack.com',                category:'Chat',        tags:['chat','team','messaging'],         rating:4.6, reviews:'120K', description:'Your productivity platform for team collaboration.'},
  {id:'biz3', name:'Trello',        domain:'trello.com',            homeCategory:'business',     mode:'work',  emoji:'📋', url:'https://trello.com',               category:'Kanban',      tags:['tasks','kanban','project'],        rating:4.7, reviews:'80K',  description:'Organize your work with boards, lists and cards.'},
  {id:'biz4', name:'Zoom',          domain:'zoom.us',               homeCategory:'business',     mode:'work',  emoji:'📹', url:'https://zoom.us',                  category:'Video',       tags:['meetings','video','calls'],        rating:4.5, reviews:'500K', description:'Video meetings, webinars, and phone calls.'},
  {id:'biz5', name:'Linear',        domain:'linear.app',            homeCategory:'business',     mode:'work',  emoji:'🔷', url:'https://linear.app',               category:'Projects',    tags:['issues','sprints','engineering'],  rating:4.8, reviews:'15K',  description:'The issue tracker built for modern software teams.'},
  {id:'biz6', name:'Loom',          domain:'loom.com',              homeCategory:'business',     mode:'work',  emoji:'🎥', url:'https://www.loom.com',              category:'Video',       tags:['video','record','async'],          rating:4.7, reviews:'25K',  description:'Record quick video messages for your team.'},
  // BEAUTY
  {id:'bty1', name:'Pinterest',     domain:'pinterest.com',         homeCategory:'beauty',       mode:'play',  emoji:'📌', url:'https://www.pinterest.com',         category:'Inspiration', tags:['beauty','fashion','ideas'],        rating:4.7, reviews:'500K', description:'Discover ideas for beauty, fashion, home and more.'},
  {id:'bty2', name:'Canva',         domain:'canva.com',             homeCategory:'beauty',       mode:'work',  emoji:'✏️', url:'https://www.canva.com',             category:'Design',      tags:['beauty','design','templates'],     rating:4.8, reviews:'180K', description:'Create stunning beauty content and social posts.'},
  {id:'bty3', name:'VSCO',          domain:'vsco.co',               homeCategory:'beauty',       mode:'play',  emoji:'📷', url:'https://vsco.co',                  category:'Photo',       tags:['photo','filter','beauty'],         rating:4.6, reviews:'90K',  description:'Edit your photos and videos with creative tools.'},
  {id:'bty4', name:'Lightroom',     domain:'adobe.com',             homeCategory:'beauty',       mode:'work',  emoji:'🌅', url:'https://lightroom.adobe.com',       category:'Photo',       tags:['photo','edit','adobe'],            rating:4.7, reviews:'150K', description:'Professional photo editing anywhere, anytime.'},
  {id:'bty5', name:'YouCam',        domain:'perfectcorp.com',       homeCategory:'beauty',       mode:'play',  emoji:'💅', url:'https://www.perfectcorp.com',       category:'Makeup',      tags:['makeup','beauty','try-on'],        rating:4.5, reviews:'40K',  description:'Virtual makeup try-on powered by AI.'},
  {id:'bty6', name:'Unfold',        domain:'unfold.com',            homeCategory:'beauty',       mode:'play',  emoji:'🌸', url:'https://unfold.com',                category:'Stories',     tags:['stories','beauty','templates'],    rating:4.6, reviews:'35K',  description:'Create beautiful stories with aesthetic templates.'},
  // ART & DESIGN
  {id:'art1', name:'Figma',         domain:'figma.com',             homeCategory:'artdesign',    mode:'work',  emoji:'🎨', url:'https://www.figma.com',             category:'Design',      tags:['design','ui','prototype'],         rating:4.9, reviews:'60K',  description:'The collaborative interface design tool.'},
  {id:'art2', name:'Adobe XD',      domain:'adobe.com',             homeCategory:'artdesign',    mode:'work',  emoji:'🔵', url:'https://www.adobe.com/products/xd.html', category:'Design',tags:['design','adobe','ux'],            rating:4.6, reviews:'45K',  description:'Design and prototype user experiences with Adobe XD.'},
  {id:'art3', name:'Spline',        domain:'spline.design',         homeCategory:'artdesign',    mode:'work',  emoji:'🌀', url:'https://spline.design',             category:'3D',          tags:['3d','design','interactive'],       rating:4.7, reviews:'12K',  description:'Design and collaborate in 3D with ease.'},
  {id:'art4', name:'Procreate',     domain:'procreate.com',         homeCategory:'artdesign',    mode:'play',  emoji:'🖌️', url:'https://procreate.com',             category:'Drawing',     tags:['drawing','illustration','art'],    rating:4.9, reviews:'200K', description:'Powerful illustration app for creative professionals.'},
  {id:'art5', name:'Coolors',       domain:'coolors.co',            homeCategory:'artdesign',    mode:'work',  emoji:'🌈', url:'https://coolors.co',               category:'Colors',      tags:['colors','palette','design'],       rating:4.7, reviews:'20K',  description:'Generate beautiful color palettes in seconds.'},
  {id:'art6', name:'Dribbble',      domain:'dribbble.com',          homeCategory:'artdesign',    mode:'work',  emoji:'🏀', url:'https://dribbble.com',              category:'Portfolio',   tags:['design','portfolio','inspiration'],rating:4.6, reviews:'40K',  description:'Discover the world\'s top designers and creatives.'},
  // FINANCE
  {id:'fin1', name:'PayPal',        domain:'paypal.com',            homeCategory:'finance',      mode:'work',  emoji:'💰', url:'https://www.paypal.com',            category:'Payments',    tags:['payments','money','transfer'],     rating:4.5, reviews:'600K', description:'Send and receive money safely with PayPal.'},
  {id:'fin2', name:'Wise',          domain:'wise.com',              homeCategory:'finance',      mode:'work',  emoji:'🌍', url:'https://wise.com',                  category:'Transfer',    tags:['money','international','transfer'],rating:4.7, reviews:'80K',  description:'Send money abroad at real exchange rates.'},
  {id:'fin3', name:'CoinGecko',     domain:'coingecko.com',         homeCategory:'finance',      mode:'work',  emoji:'🦎', url:'https://www.coingecko.com',         category:'Crypto',      tags:['crypto','bitcoin','prices'],       rating:4.6, reviews:'30K',  description:'Track crypto prices, charts and market data.'},
  {id:'fin4', name:'Yahoo Finance', domain:'yahoo.com',             homeCategory:'finance',      mode:'work',  emoji:'📈', url:'https://finance.yahoo.com',         category:'Stocks',      tags:['stocks','finance','market'],       rating:4.5, reviews:'200K', description:'Stock quotes, financial news, and portfolio tracking.'},
  {id:'fin5', name:'YNAB',          domain:'youneedabudget.com',    homeCategory:'finance',      mode:'work',  emoji:'📊', url:'https://www.youneedabudget.com',    category:'Budget',      tags:['budget','money','savings'],        rating:4.8, reviews:'25K',  description:'Stop living paycheck to paycheck with smart budgeting.'},
  {id:'fin6', name:'Coinbase',      domain:'coinbase.com',          homeCategory:'finance',      mode:'work',  emoji:'🪙', url:'https://www.coinbase.com',          category:'Crypto',      tags:['crypto','buy','exchange'],         rating:4.4, reviews:'150K', description:'Buy, sell, and manage your cryptocurrency portfolio.'},
  // EDUCATION
  {id:'edu1', name:'Khan Academy',  domain:'khanacademy.org',       homeCategory:'education',    mode:'study', emoji:'📚', url:'https://www.khanacademy.org',       category:'Learning',    tags:['learning','math','science'],       rating:4.8, reviews:'45K',  description:'Free world-class education for anyone, anywhere.'},
  {id:'edu2', name:'Coursera',      domain:'coursera.org',          homeCategory:'education',    mode:'study', emoji:'🎓', url:'https://www.coursera.org',          category:'Courses',     tags:['courses','certificates'],          rating:4.7, reviews:'60K',  description:'Learn from world-class universities and companies.'},
  {id:'edu3', name:'Quizlet',       domain:'quizlet.com',           homeCategory:'education',    mode:'study', emoji:'🃏', url:'https://quizlet.com',               category:'Flashcards',  tags:['flashcards','memory','study'],     rating:4.7, reviews:'55K',  description:'Make flashcards and study smarter.'},
  {id:'edu4', name:'Wolfram Alpha', domain:'wolframalpha.com',      homeCategory:'education',    mode:'study', emoji:'🔢', url:'https://www.wolframalpha.com',      category:'Calculator',  tags:['math','calculator','answers'],     rating:4.7, reviews:'8K',   description:'Computational intelligence for any question.'},
  {id:'edu5', name:'Desmos',        domain:'desmos.com',            homeCategory:'education',    mode:'study', emoji:'📐', url:'https://www.desmos.com',            category:'Calculator',  tags:['math','graphing'],                 rating:4.7, reviews:'8K',   description:'Powerful graphing calculator for math and science.'},
  {id:'edu6', name:'MIT OpenCourse',domain:'mit.edu',               homeCategory:'education',    mode:'study', emoji:'🏛️', url:'https://ocw.mit.edu',               category:'Courses',     tags:['university','courses','free'],     rating:4.8, reviews:'20K',  description:'Free MIT courseware — learn from the best university.'},
  // ENTERTAINMENT
  {id:'ent1', name:'YouTube',       domain:'youtube.com',           homeCategory:'entertainment',mode:'play',  emoji:'▶️', url:'https://www.youtube.com',           category:'Video',       tags:['video','music','entertainment'],   rating:4.8, reviews:'1M',   description:'Watch, share and discover videos worldwide.'},
  {id:'ent2', name:'Spotify',       domain:'spotify.com',           homeCategory:'entertainment',mode:'play',  emoji:'🎵', url:'https://open.spotify.com',          category:'Music',       tags:['music','podcast','audio'],         rating:4.9, reviews:'900K', description:'Music for everyone, free and ad-supported.'},
  {id:'ent3', name:'Twitch',        domain:'twitch.tv',             homeCategory:'entertainment',mode:'play',  emoji:'🟣', url:'https://www.twitch.tv',             category:'Streaming',   tags:['streaming','gaming','live'],       rating:4.7, reviews:'150K', description:'Watch live game streams and connect with creators.'},
  {id:'ent4', name:'Reddit',        domain:'reddit.com',            homeCategory:'entertainment',mode:'play',  emoji:'🤖', url:'https://www.reddit.com',            category:'Social',      tags:['social','community','news'],       rating:4.5, reviews:'400K', description:'The front page of the internet.'},
  {id:'ent5', name:'SoundCloud',    domain:'soundcloud.com',        homeCategory:'entertainment',mode:'play',  emoji:'🔊', url:'https://soundcloud.com',            category:'Music',       tags:['music','indie','upload'],          rating:4.6, reviews:'60K',  description:'Discover and share music from independent artists.'},
  {id:'ent6', name:'GeoGuessr',     domain:'geoguessr.com',         homeCategory:'entertainment',mode:'play',  emoji:'🌍', url:'https://www.geoguessr.com',         category:'Game',        tags:['geography','maps','explore'],      rating:4.7, reviews:'30K',  description:'Explore the world through Google Street View.'},
  // TOOLS
  {id:'tol1', name:'Smallpdf',      domain:'smallpdf.com',          homeCategory:'tools',        mode:'study', emoji:'📋', url:'https://smallpdf.com',              category:'PDF Tools',   tags:['pdf','compress','convert'],        rating:4.6, reviews:'30K',  description:'All-in-one PDF tool — compress, convert, edit.'},
  {id:'tol2', name:'iLovePDF',      domain:'ilovepdf.com',          homeCategory:'tools',        mode:'study', emoji:'❤️', url:'https://www.ilovepdf.com',          category:'PDF',         tags:['pdf','merge','split'],             rating:4.7, reviews:'18K',  description:'Merge, split, compress and convert PDFs with ease.'},
  {id:'tol3', name:'Pomofocus',     domain:'pomofocus.io',          homeCategory:'tools',        mode:'study', emoji:'🍅', url:'https://pomofocus.io',              category:'Focus',       tags:['pomodoro','focus','timer'],        rating:4.5, reviews:'6K',   description:'A Pomodoro timer to stay focused on your tasks.'},
  {id:'tol4', name:'GitHub',        domain:'github.com',            homeCategory:'tools',        mode:'work',  emoji:'🐙', url:'https://github.com',               category:'Code',        tags:['code','git','repository'],         rating:4.8, reviews:'100K', description:'Where the world builds software together.'},
  {id:'tol5', name:'Google Docs',   domain:'google.com',            homeCategory:'tools',        mode:'study', emoji:'📄', url:'https://docs.google.com',           category:'Documents',   tags:['docs','writing','google'],         rating:4.8, reviews:'500K', description:'Create and collaborate on documents in real time.'},
  {id:'tol6', name:'Miro',          domain:'miro.com',              homeCategory:'tools',        mode:'work',  emoji:'🖼️', url:'https://miro.com',                  category:'Whiteboard',  tags:['whiteboard','brainstorm'],         rating:4.7, reviews:'40K',  description:'The collaborative online whiteboard platform.'},
  // HEALTH
  {id:'hlt1', name:'MyFitnessPal',  domain:'myfitnesspal.com',      homeCategory:'health',       mode:'play',  emoji:'🏃', url:'https://www.myfitnesspal.com',      category:'Fitness',     tags:['fitness','calories','diet'],       rating:4.6, reviews:'200K', description:'Track your food and exercise to reach your fitness goals.'},
  {id:'hlt2', name:'Headspace',     domain:'headspace.com',         homeCategory:'health',       mode:'play',  emoji:'🧘', url:'https://www.headspace.com',         category:'Meditation',  tags:['meditation','sleep','mindfulness'],rating:4.7, reviews:'100K', description:'Meditation and mindfulness for any mind, any mood.'},
  {id:'hlt3', name:'Calm',          domain:'calm.com',              homeCategory:'health',       mode:'play',  emoji:'😌', url:'https://www.calm.com',              category:'Wellness',    tags:['sleep','meditation','calm'],       rating:4.8, reviews:'150K', description:'Sleep, meditation, and relaxation app.'},
  {id:'hlt4', name:'Strava',        domain:'strava.com',            homeCategory:'health',       mode:'play',  emoji:'🚴', url:'https://www.strava.com',            category:'Running',     tags:['running','cycling','fitness'],     rating:4.6, reviews:'80K',  description:'Track your runs, rides, and workouts with GPS.'},
  {id:'hlt5', name:'Cronometer',    domain:'cronometer.com',        homeCategory:'health',       mode:'play',  emoji:'🥗', url:'https://cronometer.com',            category:'Nutrition',   tags:['nutrition','food','health'],       rating:4.7, reviews:'30K',  description:'Track your nutrition and health data accurately.'},
  {id:'hlt6', name:'Noom',          domain:'noom.com',              homeCategory:'health',       mode:'play',  emoji:'🌿', url:'https://www.noom.com',              category:'Diet',        tags:['weight','diet','coaching'],        rating:4.4, reviews:'60K',  description:'Behavior-based approach to sustainable weight loss.'},
  // SOCIAL
  {id:'soc1', name:'Twitter / X',   domain:'twitter.com',           homeCategory:'social',       mode:'play',  emoji:'🐦', url:'https://twitter.com',              category:'Social',      tags:['social','news','trending'],        rating:4.3, reviews:'800K', description:'See what\'s happening in the world right now.'},
  {id:'soc2', name:'LinkedIn',      domain:'linkedin.com',          homeCategory:'social',       mode:'work',  emoji:'💼', url:'https://www.linkedin.com',          category:'Network',     tags:['social','jobs','professional'],    rating:4.5, reviews:'500K', description:'Professional networking and job search platform.'},
  {id:'soc3', name:'Discord',       domain:'discord.com',           homeCategory:'social',       mode:'play',  emoji:'🎮', url:'https://discord.com',              category:'Chat',        tags:['chat','gaming','community'],       rating:4.7, reviews:'300K', description:'Voice, video, and text communication for communities.'},
  {id:'soc4', name:'Telegram',      domain:'telegram.org',          homeCategory:'social',       mode:'play',  emoji:'✈️', url:'https://web.telegram.org',         category:'Messaging',   tags:['messaging','private','groups'],    rating:4.8, reviews:'400K', description:'Fast, secure, and powerful messaging app.'},
  {id:'soc5', name:'WhatsApp',      domain:'whatsapp.com',          homeCategory:'social',       mode:'play',  emoji:'📱', url:'https://web.whatsapp.com',          category:'Messaging',   tags:['messaging','calls','family'],      rating:4.7, reviews:'1M',   description:'Simple, reliable, private messaging and calling.'},
  {id:'soc6', name:'Mastodon',      domain:'mastodon.social',       homeCategory:'social',       mode:'play',  emoji:'🐘', url:'https://mastodon.social',           category:'Social',      tags:['social','open source','fediverse'],rating:4.3, reviews:'15K',  description:'Free and open-source decentralized social network.'},
];


// ── GAMES DATA ────────────────────────────────────────────────────────────────
const GAMES = [
  // PUZZLE
  {id:'g-puz1', name:'2048',           domain:'play2048.co',        gameCategory:'puzzle',   emoji:'🔢', url:'https://play2048.co',              category:'Puzzle',   tags:['puzzle','numbers','merge'],      rating:4.8, reviews:'200K', description:'Merge tiles to reach 2048 in this addictive number puzzle.'},
  {id:'g-puz2', name:'Jigsaw Planet',  domain:'jigsawplanet.com',   gameCategory:'puzzle',   emoji:'🧩', url:'https://www.jigsawplanet.com',     category:'Puzzle',   tags:['jigsaw','puzzle','relax'],       rating:4.6, reviews:'80K',  description:'Play thousands of free jigsaw puzzles online.'},
  {id:'g-puz3', name:'Unblock Me',     domain:'coolmathgames.com',  gameCategory:'puzzle',   emoji:'📦', url:'https://www.coolmathgames.com/0-unblock-me', category:'Puzzle', tags:['sliding','block','puzzle'], rating:4.5, reviews:'50K',  description:'Slide blocks to clear the path — satisfying brain teaser.'},
  {id:'g-puz4', name:'Sudoku.com',     domain:'sudoku.com',         gameCategory:'puzzle',   emoji:'🔣', url:'https://sudoku.com',               category:'Logic',    tags:['sudoku','logic','numbers'],      rating:4.9, reviews:'1M',   description:'The classic Sudoku puzzle with millions of unique boards.'},
  {id:'g-puz5', name:'Nonograms',      domain:'nonograms.org',      gameCategory:'puzzle',   emoji:'🎯', url:'https://www.nonograms.org',        category:'Puzzle',   tags:['nonogram','picross','logic'],    rating:4.7, reviews:'30K',  description:'Solve pixel art logic puzzles with number clues.'},
  {id:'g-puz6', name:'Mahjong',        domain:'mahjong.com',        gameCategory:'puzzle',   emoji:'🀄', url:'https://www.mahjong.com',          category:'Puzzle',   tags:['mahjong','tiles','classic'],     rating:4.6, reviews:'120K', description:'Classic Mahjong solitaire tile matching game.'},
  // ACTION
  {id:'g-act1', name:'Shell Shockers', domain:'shellshock.io',      gameCategory:'action',   emoji:'🥚', url:'https://shellshock.io',            category:'Shooter',  tags:['fps','eggs','multiplayer'],      rating:4.7, reviews:'500K', description:'Egg-based FPS game — battle other players online.'},
  {id:'g-act2', name:'Krunker.io',     domain:'krunker.io',         gameCategory:'action',   emoji:'🎯', url:'https://krunker.io',               category:'FPS',      tags:['fps','shooter','online'],        rating:4.8, reviews:'800K', description:'Fast-paced browser FPS with pixel-art style graphics.'},
  {id:'g-act3', name:'Bullet Force',   domain:'bulletforce.io',     gameCategory:'action',   emoji:'💥', url:'https://www.bulletforce.io',       category:'FPS',      tags:['fps','3d','multiplayer'],        rating:4.6, reviews:'200K', description:'3D multiplayer FPS with realistic weapons and maps.'},
  {id:'g-act4', name:'Venge.io',       domain:'venge.io',           gameCategory:'action',   emoji:'⚔️', url:'https://venge.io',                 category:'FPS',      tags:['fps','3d','competitive'],        rating:4.7, reviews:'150K', description:'Competitive 3D FPS with smooth browser gameplay.'},
  {id:'g-act5', name:'Stabfish 2',     domain:'stabfish2.io',       gameCategory:'action',   emoji:'🐡', url:'https://stabfish2.io',             category:'Action',   tags:['fish','battle','io'],            rating:4.4, reviews:'40K',  description:'Spear other fish in this chaotic underwater battle.'},
  {id:'g-act6', name:'Warbrokers',     domain:'warbrokers.io',      gameCategory:'action',   emoji:'🪖', url:'https://warbrokers.io',            category:'Battle',   tags:['war','vehicles','fps'],          rating:4.5, reviews:'60K',  description:'Team-based battle royale with vehicles and weapons.'},
  // STRATEGY
  {id:'g-str1', name:'Chess.com',      domain:'chess.com',          gameCategory:'strategy', emoji:'♟️', url:'https://www.chess.com/play/online', category:'Chess',   tags:['chess','classic','strategy'],    rating:4.9, reviews:'5M',   description:'Play chess online against players worldwide or AI.'},
  {id:'g-str2', name:'Lichess',        domain:'lichess.org',        gameCategory:'strategy', emoji:'🏰', url:'https://lichess.org',              category:'Chess',    tags:['chess','free','open-source'],    rating:4.9, reviews:'3M',   description:'Free, open-source chess server. No ads, no tracking.'},
  {id:'g-str3', name:'Colonist.io',    domain:'colonist.io',        gameCategory:'strategy', emoji:'🏝️', url:'https://colonist.io',              category:'Board',    tags:['catan','settlers','strategy'],   rating:4.8, reviews:'400K', description:'Play Settlers of Catan online with friends for free.'},
  {id:'g-str4', name:'Skribbl.io',     domain:'skribbl.io',         gameCategory:'strategy', emoji:'✏️', url:'https://skribbl.io',               category:'Drawing',  tags:['drawing','guess','party'],       rating:4.7, reviews:'700K', description:'Multiplayer drawing and guessing game — play with friends.'},
  {id:'g-str5', name:'Risiko Online',  domain:'warzone.com',        gameCategory:'strategy', emoji:'🌍', url:'https://www.warzone.com',          category:'Strategy', tags:['risk','world','domination'],     rating:4.6, reviews:'100K', description:'Conquer the world in this online Risk strategy game.'},
  {id:'g-str6', name:'Generals.io',   domain:'generals.io',         gameCategory:'strategy', emoji:'🗺️', url:'https://generals.io',              category:'RTS',      tags:['rts','strategy','conquest'],     rating:4.7, reviews:'80K',  description:'Real-time strategy game — expand your territory and conquer.'},
  // ARCADE
  {id:'g-arc1', name:'Pac-Man',        domain:'google.com',         gameCategory:'arcade',   emoji:'👾', url:'https://www.google.com/logos/2010/pacman10-i.html', category:'Classic', tags:['pacman','classic','arcade'], rating:4.9, reviews:'2M',   description:'The timeless Google Pac-Man — eat dots, dodge ghosts.'},
  {id:'g-arc2', name:'Agar.io',        domain:'agar.io',            gameCategory:'arcade',   emoji:'🔵', url:'https://agar.io',                  category:'io Game',  tags:['cells','eat','grow'],            rating:4.6, reviews:'2M',   description:'Grow your cell by eating others in this classic io game.'},
  {id:'g-arc3', name:'Slither.io',     domain:'slither.io',         gameCategory:'arcade',   emoji:'🐍', url:'https://slither.io',               category:'Snake',    tags:['snake','grow','io'],             rating:4.5, reviews:'3M',   description:'Grow your snake and dominate the leaderboard.'},
  {id:'g-arc4', name:'Diep.io',        domain:'diep.io',            gameCategory:'arcade',   emoji:'🔫', url:'https://diep.io',                  category:'io Game',  tags:['tanks','shoot','upgrade'],       rating:4.6, reviews:'1M',   description:'Upgrade your tank and defeat enemies in Diep.io.'},
  {id:'g-arc5', name:'Curvefever',     domain:'curvefever.pro',     gameCategory:'arcade',   emoji:'〰️', url:'https://curvefever.pro',           category:'Arcade',   tags:['curve','trails','multiplayer'],  rating:4.5, reviews:'200K', description:'Draw curves and trap your opponents in this fun game.'},
  {id:'g-arc6', name:'Wings.io',       domain:'wings.io',           gameCategory:'arcade',   emoji:'✈️', url:'https://wings.io',                 category:'Aerial',   tags:['planes','shoot','aerial'],       rating:4.4, reviews:'150K', description:'Fly and shoot down enemy planes in this aerial io game.'},
  // WORD
  {id:'g-wrd1', name:'Wordle',         domain:'nytimes.com',        gameCategory:'word',     emoji:'📰', url:'https://www.nytimes.com/games/wordle/index.html', category:'Word', tags:['wordle','word','daily'],    rating:4.9, reviews:'10M',  description:'Guess the 5-letter word in 6 tries. Daily challenge.'},
  {id:'g-wrd2', name:'Typeracer',      domain:'typeracer.com',      gameCategory:'word',     emoji:'⌨️', url:'https://play.typeracer.com',       category:'Typing',   tags:['typing','speed','race'],         rating:4.7, reviews:'500K', description:'Race against others by typing text as fast as you can.'},
  {id:'g-wrd3', name:'Codenames',      domain:'codenames.game',     gameCategory:'word',     emoji:'🕵️', url:'https://codenames.game',           category:'Party',    tags:['codenames','spy','clues'],       rating:4.8, reviews:'200K', description:'Spy-themed word guessing game for teams.'},
  {id:'g-wrd4', name:'WordHurdle',     domain:'wordhurdle.in',      gameCategory:'word',     emoji:'🏃', url:'https://wordhurdle.in',            category:'Word',     tags:['word','hurdle','puzzle'],        rating:4.6, reviews:'80K',  description:'A challenging 6-letter word guessing game.'},
  {id:'g-wrd5', name:'Heardle',        domain:'heardle.app',        gameCategory:'word',     emoji:'🎵', url:'https://www.spotify.com/heardle',  category:'Music',    tags:['music','guess','audio'],         rating:4.7, reviews:'300K', description:'Guess the song from its intro — daily music game.'},
  {id:'g-wrd6', name:'Worldle',        domain:'worldle.teuteuf.fr', gameCategory:'word',     emoji:'🌐', url:'https://worldle.teuteuf.fr',       category:'Geography',tags:['country','geography','daily'],   rating:4.7, reviews:'400K', description:'Guess the country by its shape. Daily geography challenge.'},
  // CASUAL
  {id:'g-cas1', name:'Cookie Clicker', domain:'orteil.dashnet.org', gameCategory:'casual',   emoji:'🍪', url:'https://orteil.dashnet.org/cookieclicker', category:'Idle', tags:['idle','clicker','cookies'],     rating:4.7, reviews:'2M',   description:'Click cookies to build your cookie empire.'},
  {id:'g-cas2', name:'Numberle',       domain:'numberle.net',       gameCategory:'casual',   emoji:'🔢', url:'https://numberle.net',             category:'Numbers',  tags:['numbers','math','casual'],       rating:4.4, reviews:'50K',  description:'Wordle but for equations — guess the math formula.'},
  {id:'g-cas3', name:'Gartic Phone',   domain:'garticphone.com',    gameCategory:'casual',   emoji:'📞', url:'https://garticphone.com',          category:'Party',    tags:['drawing','telephone','party'],   rating:4.8, reviews:'1M',   description:'Broken Telephone with drawings — hilarious party game.'},
  {id:'g-cas4', name:'Geoguessr',      domain:'geoguessr.com',      gameCategory:'casual',   emoji:'📍', url:'https://www.geoguessr.com',        category:'Geography',tags:['maps','explore','travel'],       rating:4.8, reviews:'500K', description:'Guess your location from Street View images.'},
  {id:'g-cas5', name:'Sporcle',        domain:'sporcle.com',        gameCategory:'casual',   emoji:'📚', url:'https://www.sporcle.com',          category:'Trivia',   tags:['trivia','quiz','facts'],         rating:4.6, reviews:'300K', description:'Thousands of trivia quizzes on every topic imaginable.'},
  {id:'g-cas6', name:'Akinator',       domain:'akinator.com',       gameCategory:'casual',   emoji:'🧞', url:'https://en.akinator.com',          category:'AI',       tags:['guess','ai','characters'],       rating:4.7, reviews:'400K', description:'Can the AI genie guess who you are thinking of?'},
  // SPORTS
  {id:'g-spt1', name:'Penalty Shootout',domain:'penaltyshootouttournament.com',gameCategory:'sports',emoji:'⚽',url:'https://www.penaltyshootouttournament.com',category:'Football',tags:['soccer','penalty','kick'],rating:4.5,reviews:'100K',description:'Take penalties in this intense browser football game.'},
  {id:'g-spt2', name:'Basketball Stars',domain:'poki.com',          gameCategory:'sports',   emoji:'🏀', url:'https://poki.com/en/g/basketball-stars', category:'Basketball',tags:['basketball','dunk','sport'],  rating:4.6, reviews:'200K', description:'Play basketball against opponents in this slick arcade game.'},
  {id:'g-spt3', name:'Table Tennis',   domain:'miniclip.com',       gameCategory:'sports',   emoji:'🏓', url:'https://www.miniclip.com/games/table-tennis/en/', category:'Ping Pong',tags:['table tennis','ping pong','sport'],rating:4.5,reviews:'80K',description:'Fast-paced online table tennis with smooth controls.'},
  {id:'g-spt4', name:'Golf Online',    domain:'minigolf.com',       gameCategory:'sports',   emoji:'⛳', url:'https://www.minigolf.com',         category:'Golf',     tags:['golf','mini','sport'],           rating:4.4, reviews:'60K',  description:'Play mini golf with friends online in the browser.'},
  {id:'g-spt5', name:'Dino Chrome',    domain:'google.com',         gameCategory:'sports',   emoji:'🦕', url:'chrome://dino',                    category:'Endless',  tags:['dino','chrome','run'],           rating:4.9, reviews:'∞',    description:"Google Chrome's hidden offline dinosaur runner game."},
  {id:'g-spt6', name:'8 Ball Pool',    domain:'miniclip.com',       gameCategory:'sports',   emoji:'🎱', url:'https://www.miniclip.com/games/8-ball-pool/en/', category:'Pool',tags:['billiards','pool','8-ball'],    rating:4.7, reviews:'5M',   description:'Play pool online against players worldwide.'},
  // ADVENTURE
  {id:'g-adv1', name:'Little Alchemy 2',domain:'littlealchemy2.com',gameCategory:'adventure',emoji:'⚗️', url:'https://littlealchemy2.com',       category:'Crafting', tags:['combine','craft','elements'],    rating:4.8, reviews:'1M',   description:'Combine elements to discover hundreds of new items.'},
  {id:'g-adv2', name:'Torn City',      domain:'torn.com',           gameCategory:'adventure',emoji:'🏙️', url:'https://www.torn.com',             category:'RPG',      tags:['rpg','crime','city'],            rating:4.4, reviews:'50K',  description:'Browser-based crime RPG set in a persistent city.'},
  {id:'g-adv3', name:'Incredibox',     domain:'incredibox.com',     gameCategory:'adventure',emoji:'🎧', url:'https://www.incredibox.com',       category:'Music',    tags:['music','beats','creative'],      rating:4.8, reviews:'2M',   description:'Create your own beatbox music with animated characters.'},
  {id:'g-adv4', name:'Idle Breakout',  domain:'kodiqi.com',         gameCategory:'adventure',emoji:'🧱', url:'https://kodiqi.com/game/idle-breakout', category:'Idle',tags:['breakout','idle','bricks'],      rating:4.6, reviews:'300K', description:'Idle Breakout — upgrade your balls to smash all the bricks.'},
  {id:'g-adv5', name:'Doodle God',     domain:'doodlegod.com',      gameCategory:'adventure',emoji:'⚡', url:'https://www.doodlegod.com',        category:'God Game', tags:['combine','create','universe'],   rating:4.5, reviews:'200K', description:'Combine elements to create the universe from scratch.'},
  {id:'g-adv6', name:'Evolvo.io',      domain:'evolvo.io',          gameCategory:'adventure',emoji:'🐠', url:'https://evolvo.io',                category:'Evolution',tags:['evolve','eat','grow'],           rating:4.5, reviews:'80K',  description:'Eat food, evolve your creature, and dominate the ocean.'},
];

const ALL_APPS = APPS;

const MODE_CFG = {
  study:{label:'Study', emoji:'🎓', subtitle:'Notes, calculators, AI tools and more', grad:'from-violet-600 to-indigo-800'},
  work: {label:'Work',  emoji:'💼', subtitle:'Documents, tools, productivity',         grad:'from-blue-600 to-blue-900'   },
  play: {label:'Play',  emoji:'🎮', subtitle:'Games, fun tools and entertainment',     grad:'from-emerald-500 to-green-800'},
};

function getAppsByHomeCategory(catId) {
  return APPS.filter(a => a.homeCategory === catId);
}

function getGamesByCategory(catId) {
  return GAMES.filter(g => g.gameCategory === catId);
}
